apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: e2e-test-coverage
  namespace: e2e-test-coverage
  labels:
    app.kubernetes.io/name: e2e-test-coverage
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: public
  rules:
    - host: testandwin.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: e2e-test-coverage
                port:
                  name: http
    - host: www.testandwin.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: e2e-test-coverage
                port:
                  name: http
  # TLS configuration
  tls:
    - hosts:
        - testandwin.de
        - www.testandwin.de
      secretName: e2e-test-coverage-tls
