apiVersion: v1
kind: Service
metadata:
  name: e2e-test-coverage
  namespace: e2e-test-coverage
  labels:
    app.kubernetes.io/name: e2e-test-coverage
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      nodePort: 30081
  selector:
    app.kubernetes.io/name: e2e-test-coverage
